kind: pipeline
type: kubernetes
name: buildimage

trigger:
  event:
    exclude:
      - promote

steps:
  - name: build
    image: adoptopenjdk/openjdk11
    user: 0
    commands:
      - chmod +rwx ./mvnw
      - ./mvnw package -Dquarkus.package.type=fast-jar 

  - name: docker
    image: plugins/docker
    settings:
      repo: modeseven/${DRONE_REPO_NAME}
      dockerfile: src/main/docker/Dockerfile.fast-jar
      tags:
        - ${DRONE_SOURCE_BRANCH/\//-}
        - ${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
      cache_from:
        - modeseven/${DRONE_REPO_NAME}:${DRONE_SOURCE_BRANCH/\//-}
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
---
kind: pipeline
name: deploy staging
type: kubernetes
depends_on:
  - buildimage
trigger:
  branch:
  - develop
  event:
  - push
steps:
  - name: Update staging GITOPS cluster
    image: cloudowski/drone-kustomize
    environment:
      GIT:
        from_secret: git
      GIT_PW:
        from_secret: git_pw
    user: 0
    commands:
      - git clone https://$${GIT}:$${GIT_PW}@github.com/modeseven/cluster.git
      - cd cluster/environments/staging/
      - kustomize edit set image modeseven/${DRONE_REPO_NAME}:${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
      - git add .
      - git commit -m "Drone updated modeseven/${DRONE_REPO_NAME}:${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}"
      - git push
---
kind: pipeline
name: deploy prod
type: kubernetes

clone:
  disable: true

trigger:
  event:
  - promote
  target:
  - production

volumes:
  - name: dockersock
    temp: {}

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

steps:
  - name: pull and promote image
    image: docker:dind
    environment:
      DOCKER_LOGIN:
        from_secret: dockerhub_username
      DOCKER_PASSWORD:
        from_secret: dockerhub_password
    volumes:
    - name: dockersock
      path: /var/run
    commands:
    - sleep 15 # give docker enough time to start
    - docker ps -a  
    - echo promote to prod ${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
    - docker login -u=$${DOCKER_LOGIN} -p=$${DOCKER_PASSWORD}
    - docker pull modeseven/scheduler-api:${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
    - docker tag modeseven/scheduler-api:${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8} modeseven/scheduler-api-prod:prod-${DRONE_COMMIT_SHA:0:8}
    - docker tag modeseven/scheduler-api-prod:prod-${DRONE_COMMIT_SHA:0:8} modeseven/scheduler-api-prod:latest
    - docker push  modeseven/scheduler-api-prod:prod-${DRONE_COMMIT_SHA:0:8} 
  - name: Update prod GITOPS cluster
    image: cloudowski/drone-kustomize
    environment:
      GIT:
        from_secret: git
      GIT_PW:
        from_secret: git_pw
    user: 0
    commands:
      - git clone https://$${GIT}:$${GIT_PW}@github.com/modeseven/cluster.git
      - cd cluster/environments/production/
      - kustomize edit set image modeseven/scheduler-api-prod:prod-${DRONE_COMMIT_SHA:0:8}
      - git add .
      - git commit -m "Drone updated modeseven/scheduler-api-prod:prod-${DRONE_COMMIT_SHA:0:8}"
      - git push
